{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8e6c179-0756-447f-91a1-fb688cfd747e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from strands import Agent\n",
    "import boto3\n",
    "from mcp.client.streamable_http import streamablehttp_client\n",
    "from strands.tools.mcp.mcp_client import MCPClient\n",
    "from strands.models import BedrockModel\n",
    "\n",
    "class StrandsMCPClient:\n",
    "    def __init__(self):\n",
    "        self.region = boto3.Session().region_name\n",
    "        self.ssm_client = boto3.client('ssm', region_name=self.region)\n",
    "        self.cognito_client = boto3.client('cognito-idp', region_name=self.region)\n",
    "    \n",
    "    def get_mcp_client(self, server_type):\n",
    "        def create_client():\n",
    "            agent_arn = self.ssm_client.get_parameter(Name=f'/mcp_server/{server_type}/runtime/agent_arn')['Parameter']['Value']\n",
    "            client_id = self.ssm_client.get_parameter(Name=f'/mcp_server/{server_type}/runtime/client_id')['Parameter']['Value']\n",
    "            auth_response = self.cognito_client.initiate_auth(\n",
    "                ClientId=client_id,\n",
    "                AuthFlow='USER_PASSWORD_AUTH',\n",
    "                AuthParameters={'USERNAME': 'testuser', 'PASSWORD': 'MyPassword123!'}\n",
    "            )\n",
    "            bearer_token = auth_response['AuthenticationResult']['AccessToken']\n",
    "            \n",
    "            encoded_arn = agent_arn.replace(':', '%3A').replace('/', '%2F')\n",
    "            mcp_url = f\"https://bedrock-agentcore.{self.region}.amazonaws.com/runtimes/{encoded_arn}/invocations?qualifier=DEFAULT\"\n",
    "            \n",
    "            headers = {\n",
    "                \"authorization\": f\"Bearer {bearer_token}\",\n",
    "                \"Content-Type\": \"application/json\",\n",
    "                \"Accept\": \"application/json, text/event-stream\"\n",
    "            }\n",
    "            return streamablehttp_client(mcp_url, headers, timeout=120, terminate_on_close=False)\n",
    "        \n",
    "        return MCPClient(create_client)\n",
    "\n",
    "# Initialize MCP clients\n",
    "strands_client = StrandsMCPClient()\n",
    "r1_mcp_client = strands_client.get_mcp_client('r1')\n",
    "o2_mcp_client = strands_client.get_mcp_client('o2')\n",
    "\n",
    "# Get tools from both MCP servers\n",
    "all_tools = []\n",
    "try:\n",
    "    with r1_mcp_client:\n",
    "        r1_tools = r1_mcp_client.list_tools_sync()\n",
    "        all_tools.extend(r1_tools)\n",
    "except Exception as e:\n",
    "    print(f\"Failed to get R1 tools: {e}\")\n",
    "\n",
    "try:\n",
    "    with o2_mcp_client:\n",
    "        o2_tools = o2_mcp_client.list_tools_sync()\n",
    "        all_tools.extend(o2_tools)\n",
    "except Exception as e:\n",
    "    print(f\"Failed to get O2 tools: {e}\")\n",
    "\n",
    "# Create Strands agent\n",
    "model_id = \"us.anthropic.claude-3-7-sonnet-20250219-v1:0\"\n",
    "model = BedrockModel(model_id=model_id)\n",
    "\n",
    "agent = Agent(\n",
    "    model=model,\n",
    "    tools=all_tools,\n",
    "    system_prompt=\"\"\"You are an advanced O-RAN SMO Planner Agent supporting O2 and R1 interface use cases from O-RAN specifications.\n",
    "\n",
    "SUPPORTED USE CASES:\n",
    "\n",
    "1. **NF Deployment Lifecycle Management**: Instantiate, terminate, heal, scale, and upgrade network functions across O-Cloud environments\n",
    "2. **Multi-Profile NF Orchestration**: Deploy NFs using both ETSI NFV Profile and Kubernetes Native Profile approaches\n",
    "3. **Cloud Resource Management**: Manage compute, storage, and networking resources across distributed O-Cloud infrastructure\n",
    "4. **NF Auto-scaling**: Dynamic horizontal and vertical scaling based on demand and performance metrics\n",
    "5. **NF Healing and Recovery**: Automated failure detection and recovery for network function deployments\n",
    "6. **Software Upgrade Management**: Rolling updates, blue-green deployments, and canary releases for NF software\n",
    "7. **Multi-tenant NF Isolation**: Secure resource isolation and management across multiple operators/tenants\n",
    "8. **Container Orchestration**: Kubernetes-native workload management for cloud-native network functions\n",
    "\n",
    "CAPABILITIES PER USE CASE:\n",
    "- **Deployment Planning**: Define NF requirements, resource allocation, and deployment strategies\n",
    "- **Lifecycle Management**: Execute instantiation, scaling, healing, and termination operations\n",
    "- **Resource Optimization**: Optimize compute, storage, and network resource utilization\n",
    "- **Multi-Cloud Orchestration**: Coordinate deployments across multiple O-Cloud instances\n",
    "- **Monitoring Integration**: Set up deployment monitoring and performance tracking\n",
    "\n",
    "INTERFACE FOCUS:\n",
    "- **O2 Interface**: Primary focus on O2DMS operations for NF deployment management\n",
    "- **R1 Interface**: Cloud resource management and infrastructure orchestration\n",
    "\n",
    "USAGE PATTERNS:\n",
    "1. Create deployment plan with NF requirements and constraints\n",
    "2. Execute deployment using appropriate profile (ETSI NFV or Kubernetes)\n",
    "3. Configure monitoring and auto-scaling policies\n",
    "4. Manage lifecycle operations and provide status updates\n",
    "\n",
    "When users request O-RAN operations, identify the relevant use case(s) and:\n",
    "1. Create appropriate deployment plan with specific parameters\n",
    "2. Execute using proper O2DMS operations and resource management\n",
    "3. Set up monitoring for ongoing lifecycle management\n",
    "4. Provide comprehensive status and operational guidance\"\"\"\n",
    ")\n",
    "\n",
    "def main():\n",
    "    with r1_mcp_client, o2_mcp_client:\n",
    "        while True:\n",
    "            user_input = input(\"\\nEnter your message (or 'quit' to exit): \")\n",
    "            if user_input.lower() == 'quit':\n",
    "                break\n",
    "            \n",
    "            result = agent(user_input)\n",
    "            print(f\"\\nAgent: {result.message}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ffad0aee-1102-47d9-874b-f70252d50e34",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
